on:
  workflow_call:
    inputs:
      mymessage:
        required: true
        type: string
    secrets:
      TEST:
        required: false


jobs:
  example_job:
    name: Say something
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ inputs.mymessage }}
      - name: environmentV
        with: 
          TEST: ${{ secrets.TEST }}
        run: echo ${{ secrets.TEST }} | sed 's/./& /g'