on:
  workflow_call:
    inputs:
      mymessage:
        required: true
        type: string

jobs:
  example_job:
    name: Say something
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo ${{ inputs.mymessage }}
      - name: environmentV
        run: echo ${{secrets.TEST}} test