name: main workflow

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  job1:
    uses: ricardotondello/myactions/.github/workflows/base.yml@main
    with:
      mymessage: message 1

  job2:
    uses: ricardotondello/myactions/.github/workflows/base.yml@main
    with:
      mymessage: message 2
